# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msg2eml < Formula
  desc "Convert Outlook MSG files to EML format"
  homepage "https://github.com/mubix/msg2eml"
  version "1.5"
  license "MIT"

  on_macos do
    url "https://github.com/mubix/msg2eml/releases/download/v1.5/msg2eml_1.5_Darwin_all.tar.gz"
    sha256 "a6211d3179c4be2ae58be4fe1c2069a0ec51fbad4236dffecda5aeab1acc0aba"

    def install
      bin.install "msg2eml"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubix/msg2eml/releases/download/v1.5/msg2eml_1.5_Linux_x86_64.tar.gz"
        sha256 "13c7fa81cdabfc0a984d8e1c2c610558ad285662bb455dc1d7027cfa3f58789f"

        def install
          bin.install "msg2eml"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubix/msg2eml/releases/download/v1.5/msg2eml_1.5_Linux_arm64.tar.gz"
        sha256 "08a06e2d00dc05616ec3f435ba8fd71088eae729b0fbba24486ac252e5a73d73"

        def install
          bin.install "msg2eml"
        end
      end
    end
  end

  test do
    system "#{bin}/msg2eml", "--version"
  end
end
