# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msg2eml < Formula
  desc "Convert Outlook MSG files to EML format"
  homepage "https://github.com/mubix/msg2eml"
  version "1.7"
  license "MIT"

  on_macos do
    url "https://github.com/mubix/msg2eml/releases/download/v1.7/msg2eml_1.7_Darwin_all.tar.gz"
    sha256 "35d0c57d0ba32574bc68c4c7e016278e275be55fb3f2f95465a6e599a53bc56c"

    def install
      bin.install "msg2eml"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubix/msg2eml/releases/download/v1.7/msg2eml_1.7_Linux_x86_64.tar.gz"
        sha256 "f6d5b250d7b17c618b1d0db51bb0c88bf2c03269bb108644d55f228731589b8a"

        def install
          bin.install "msg2eml"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubix/msg2eml/releases/download/v1.7/msg2eml_1.7_Linux_arm64.tar.gz"
        sha256 "2abc8e5ae2c5316946d0e65715063caab92abee5bc867033a5209f701cfe71c3"

        def install
          bin.install "msg2eml"
        end
      end
    end
  end

  test do
    system "#{bin}/msg2eml", "--version"
  end
end
