# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msg2eml < Formula
  desc "Convert Outlook MSG files to EML format"
  homepage "https://github.com/mubix/msg2eml"
  version "1.4"
  license "MIT"

  on_macos do
    url "https://github.com/mubix/msg2eml/releases/download/v1.4/msg2eml_1.4_Darwin_all.tar.gz"
    sha256 "bb01164858de144b3be752e90307ca04b2b00f6d0069c2ff49f8397143d9fa88"

    def install
      bin.install "msg2eml"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubix/msg2eml/releases/download/v1.4/msg2eml_1.4_Linux_x86_64.tar.gz"
        sha256 "6f6200e5090de17c397212b45fed430897b9d9a241ccacaf6b4e1538990f2554"

        def install
          bin.install "msg2eml"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubix/msg2eml/releases/download/v1.4/msg2eml_1.4_Linux_arm64.tar.gz"
        sha256 "d3af24f9b30c057a508e52c514715a94a2c7f29c7e137715f94941c4c1d71692"

        def install
          bin.install "msg2eml"
        end
      end
    end
  end

  test do
    system "#{bin}/msg2eml", "--version"
  end
end
